global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'online-compiler'

scrape_configs:
  - job_name: 'online-compiler-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

